"""
wallet.py — Solana keypair loader for live trading (Sprint 2 Fase 1)

Provides a LiveWallet that can sign transactions and a MockWallet used
when LIVE_TRADING_ENABLED=false (safe default; cannot sign).

Supports loading the keypair from:
1. HOT_WALLET_PRIVATE_KEY env var (base58 or JSON array format)
2. ~/.config/solana-jupiter-bot/wallet.json (generated by tools/solana_wallet.py)

Fail-safe: if LIVE_TRADING_ENABLED=false, returns MockWallet regardless
of what's configured. This prevents accidental live signing during dev.

Usage:
    from agents.wallet import load_wallet
    w = load_wallet()       # Mock in dev, Live when LIVE_TRADING_ENABLED=true
    if w.is_live:
        sig = w.sign(message_bytes)
    pubkey_str = w.pubkey
"""
from __future__ import annotations

import os
import json
import logging
from pathlib import Path
from typing import Union

log = logging.getLogger('wallet')

WALLET_FILE = Path.home() / ".config" / "solana-jupiter-bot" / "wallet.json"


def _live_trading_enabled() -> bool:
    return os.environ.get("LIVE_TRADING_ENABLED", "false").lower() == "true"


class MockWallet:
    """Safe default wallet. Exposes pubkey (if HOT_WALLET_ADDRESS set) but
    raises on sign(). Used when LIVE_TRADING_ENABLED=false."""

    is_live: bool = False

    def __init__(self, pubkey: str = ""):
        self.pubkey = pubkey or os.environ.get("HOT_WALLET_ADDRESS", "") or "MOCK_NO_PUBKEY"

    def sign(self, *args, **kwargs):
        raise RuntimeError(
            "MockWallet cannot sign transactions. "
            "Set LIVE_TRADING_ENABLED=true and configure HOT_WALLET_PRIVATE_KEY."
        )

    def __repr__(self):
        return f"<MockWallet pubkey={self.pubkey[:10]}...>"


class LiveWallet:
    """Real wallet with Ed25519 keypair. Only created when LIVE_TRADING_ENABLED=true."""

    is_live: bool = True

    def __init__(self, keypair):
        # Lazy import of solders to avoid dep failure in environments without it
        from solders.keypair import Keypair
        if not isinstance(keypair, Keypair):
            raise TypeError(f"Expected solders.keypair.Keypair, got {type(keypair)}")
        self._keypair = keypair
        self.pubkey = str(keypair.pubkey())

    def sign(self, message_bytes: bytes) -> bytes:
        """Sign arbitrary message bytes with Ed25519. Returns 64-byte signature."""
        sig = self._keypair.sign_message(message_bytes)
        return bytes(sig)

    @classmethod
    def from_env(cls) -> 'LiveWallet':
        """Load from HOT_WALLET_PRIVATE_KEY env var.
        Supports base58 string or JSON array '[1,2,3,...]' format."""
        from solders.keypair import Keypair
        key_str = (os.environ.get("HOT_WALLET_PRIVATE_KEY", "") or "").strip()
        if not key_str:
            raise ValueError("HOT_WALLET_PRIVATE_KEY not set in env")

        secret_bytes = cls._parse_key_string(key_str)
        return cls(Keypair.from_bytes(secret_bytes))

    @classmethod
    def from_file(cls, path: Path = WALLET_FILE) -> 'LiveWallet':
        """Load from wallet.json (format written by tools/solana_wallet.py)."""
        from solders.keypair import Keypair
        if not path.exists():
            raise FileNotFoundError(f"wallet file not found: {path}")
        data = json.loads(path.read_text())
        pk = data.get("private_key")
        if pk is None:
            raise ValueError(f"wallet file {path} missing 'private_key' field")
        if isinstance(pk, list):
            secret_bytes = bytes(pk)
        elif isinstance(pk, str):
            secret_bytes = cls._parse_key_string(pk)
        else:
            raise ValueError(f"wallet file {path} has unrecognized private_key type: {type(pk)}")
        return cls(Keypair.from_bytes(secret_bytes))

    @staticmethod
    def _parse_key_string(key_str: str) -> bytes:
        """Parse base58 or JSON array into raw bytes."""
        key_str = key_str.strip()
        if key_str.startswith("["):
            return bytes(json.loads(key_str))
        # Try base58 decode
        try:
            import base58
            return base58.b58decode(key_str)
        except ImportError:
            raise RuntimeError("base58 module not installed (pip install base58)")
        except Exception as e:
            raise ValueError(f"Could not parse private key (not base58 or JSON array): {e}")

    def __repr__(self):
        return f"<LiveWallet pubkey={self.pubkey[:10]}...>"


def load_wallet() -> Union[LiveWallet, MockWallet]:
    """Factory: returns LiveWallet if LIVE_TRADING_ENABLED=true AND key available,
    else MockWallet. Prefers env var over file."""
    if not _live_trading_enabled():
        log.info("LIVE_TRADING_ENABLED=false → returning MockWallet (safe default)")
        return MockWallet()

    # LIVE_TRADING_ENABLED=true — must load real wallet
    # Priority 1: env var
    try:
        return LiveWallet.from_env()
    except ValueError:
        pass
    except Exception as e:
        log.warning(f"LiveWallet.from_env failed: {e}")

    # Priority 2: wallet.json file
    if WALLET_FILE.exists():
        try:
            return LiveWallet.from_file()
        except Exception as e:
            log.warning(f"LiveWallet.from_file failed: {e}")

    # Can't load — this is fatal if LIVE_TRADING_ENABLED=true
    raise RuntimeError(
        "LIVE_TRADING_ENABLED=true but no wallet found. Either:\n"
        f"  1. Set HOT_WALLET_PRIVATE_KEY env var, or\n"
        f"  2. Run `python3 tools/solana_wallet.py --generate` to create {WALLET_FILE}"
    )
